name: barebones
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html