name: playground
version: 0.0.1
description: Playgorund for learning dart.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: any
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
