name: parnesen_client
version: 0.0.1
author: Patrick Arnesen
description: Client Side
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  parnesen_share:
    path: ../parnesen_share
  polymer: any
  quiver: any
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
