name: parnesen_client
version: 0.0.1
author: Patrick Arnesen
description: Client Side
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  crypto: any
  polymer: any
  quiver: any
  route: any
  route_hierarchical: any
  sqljocky: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/index.html
